syntax = "proto3";
import "common/proto/signature_info.proto";

package resdb.td_hotstuff;

message Certificate {
  SignatureInfo sign = 1;
  int32 view = 2;
  int32 signer = 3;
  bytes hash = 4;
  int32 slot = 6;
}

message Transaction{
  int32 id = 1;
  bytes data = 2;
  bytes hash = 3;
  int32 proxy_id = 4;
  int32 proposer = 5;
  uint64 timestamp = 6;
  int64 user_seq = 7;
  uint64 reception_time = 8;
}

enum ProposalType{
    NewMsg  = 0;
    Prepared = 1;
    Commit = 2;
    Ready_execute = 3;
}

message QC {
  repeated SignatureInfo signatures = 1;
  int32 view = 2;
  bytes hash = 3;
  int32 slot = 4;
  bytes signer_bitmap = 5;
  bytes available_signer_bitmap = 6;
  int32 collector_id = 7;
}

message TimeoutVote {
  int32 view = 1;
  int32 signer = 2;
  QC high_qc = 3;
  SignatureInfo signature = 4;
}

message TimeoutCert {
  int32 view = 1;
  QC high_qc = 2;
  bytes signer_bitmap = 3;
  repeated TimeoutVote votes = 4;
  string quorum_rule_id = 5;
}


message CandidateWeight {
  int32 validator_id = 1;
  int64 weight = 2;
}

message CandidateWeightUpdate {
  string algorithm = 1;
  uint64 window_index = 2;
  int32 window_start = 3;
  int32 window_end = 4;
  string old_weight_root = 5;
  uint64 old_weight_version = 6;
  int32 activation_view = 7;
  string metric_root = 8;
  string reputation_root = 9;
  string strong_fault_root = 10;
  string penalty_root = 11;
  string next_weight_root = 12;
  repeated CandidateWeight next_weights = 13;
  string candidate_digest = 14;
}

message WeightUpdateVote {
  int32 signer = 1;
  string old_weight_root = 2;
  uint64 old_weight_version = 3;
  int32 activation_view = 4;
  string candidate_digest = 5;
  SignatureInfo signature = 6;
}

message WeightUpdateCert {
  CandidateWeightUpdate candidate = 1;
  bytes signer_bitmap = 2;
  repeated WeightUpdateVote votes = 3;
  string quorum_rule_id = 4;
}

message Header {
  int32 proposer_id = 1;
  int32 proposal_id = 2;
  int32 view = 3;
  QC qc = 4;
  bytes prehash = 5;
  int32 slot = 6;
  bytes leader_context_hash = 7;
  TimeoutCert timeout_cert = 8;
}

message Proposal {
  Header header = 1;
  repeated Transaction transactions = 2;
  int32 sender = 3;
  bytes hash = 4;
  uint64 createtime = 5;
  SignatureInfo signature = 6;
};

enum MessageType {
  NewProposal = 0;
  Vote = 1;
  TimeoutVoteMsg = 2;
  TimeoutCertMsg = 3;
  CandidateWeightUpdateMsg = 4;
  WeightUpdateVoteMsg = 5;
  WeightUpdateCertMsg = 6;
};
