#!/bin/bash
# TD-Hotstuff invalid TimeoutCert-in-proposal strong-fault experiment for n=20.
# TD_HS_INVALID_TC_PROPOSAL_IDS is converted by deploy_multi.sh into
# replica-local TD_HS_INVALID_TC_PROPOSAL=1 only.

set -e
DEPLOY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DEPLOY_DIR"

if [ -n "${INVALID_TC_COUNTS_OVERRIDE:-}" ]; then
  COUNTS="$INVALID_TC_COUNTS_OVERRIDE"
else
  COUNTS="0 1 3"
fi

env -u TD_HS_SILENT_LEADER_IDS \
    -u TD_HS_DOUBLE_PROPOSAL_IDS -u TD_HS_DOUBLE_VOTE_IDS \
    -u TD_HS_INVALID_QC_IDS -u TD_HS_LOW_DIVERSITY_QC_IDS -u TD_HS_LOW_DIVERSITY_TARGET_IDS -u TD_HS_LOW_DIVERSITY_REVIEWER_IDS -u TD_HS_LOW_DIVERSITY_MIN_AVAILABLE_SIGNERS \
    -u TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION_IDS \
    -u TD_HS_TIMEOUT_VOTE_EQUIVOCATION_IDS \
    -u TD_HS_INVALID_TC_PROPOSAL_IDS \
    MODE_NAME="InvalidTcProposal" \
    RESULT_NAME="invalid_tc" \
    ATTACK_IDS_ENV="TD_HS_INVALID_TC_PROPOSAL_IDS" \
    DETECT_ENV="TD_HS_INVALID_TC_PROPOSAL_DETECT_ENABLE" \
    COUNTS="$COUNTS" \
    ./run_strong_fault_v2_n20.sh
