#!/bin/bash
# TD-Hotstuff WeightUpdateVote equivocation strong-fault experiment for n=20.
# TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION_IDS is converted by deploy_multi.sh
# into replica-local TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION=1 only.

set -e
DEPLOY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DEPLOY_DIR"

if [ -n "${WEIGHT_UPDATE_VOTE_EQUIVOCATION_COUNTS_OVERRIDE:-}" ]; then
  COUNTS="$WEIGHT_UPDATE_VOTE_EQUIVOCATION_COUNTS_OVERRIDE"
else
  COUNTS="0 1 3"
fi

env -u TD_HS_SILENT_LEADER_IDS \
    -u TD_HS_DOUBLE_PROPOSAL_IDS -u TD_HS_DOUBLE_VOTE_IDS \
    -u TD_HS_INVALID_QC_IDS -u TD_HS_LOW_DIVERSITY_QC_IDS -u TD_HS_LOW_DIVERSITY_TARGET_IDS -u TD_HS_LOW_DIVERSITY_REVIEWER_IDS -u TD_HS_LOW_DIVERSITY_MIN_AVAILABLE_SIGNERS \
    -u TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION_IDS \
    -u TD_HS_TIMEOUT_VOTE_EQUIVOCATION_IDS \
    -u TD_HS_INVALID_TC_PROPOSAL_IDS \
    TD_HS_WEIGHT_UPDATE_ALLOW_NOOP_CANDIDATE_ON_ATTACK=1 \
    TD_HS_WEIGHT_UPDATE_ALLOW_NOOP_INITIAL_VERSION_ONLY=1 \
    TD_HS_REPUTATION_WINDOW_SIZE="${TD_HS_REPUTATION_WINDOW_SIZE:-256}" \
    TD_HS_REPUTATION_MIN_CANDIDATE_QCS="${TD_HS_REPUTATION_MIN_CANDIDATE_QCS:-64}" \
    TD_HS_WEIGHT_UPDATE_EPOCH_VIEWS="${TD_HS_WEIGHT_UPDATE_EPOCH_VIEWS:-256}" \
    MODE_NAME="WeightUpdateVoteEquivocation" \
    RESULT_NAME="weight_update_vote_equivocation" \
    ATTACK_IDS_ENV="TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION_IDS" \
    DETECT_ENV="TD_HS_WEIGHT_UPDATE_VOTE_EQUIVOCATION_DETECT_ENABLE" \
    COUNTS="$COUNTS" \
    ./run_strong_fault_v2_n20.sh
