#!/bin/bash

# Stable defaults for TD-Hotstuff recovery experiments. Callers can override any
# value by exporting it before sourcing this file.

: "${TD_HS_WEIGHTS:=30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30}"
: "${TD_HS_REPUTATION_ENABLE:=1}"
: "${TD_HS_REPUTATION_WINDOW_SIZE:=512}"
: "${TD_HS_REPUTATION_QUEUE_CAPACITY:=65536}"
: "${TD_HS_REPUTATION_MAX_DELTA:=10}"
: "${TD_HS_REPUTATION_DECAY_PER_EPOCH:=10}"
: "${TD_HS_REPUTATION_MAX_RECOVERY_PER_EPOCH:=10}"
: "${TD_HS_REPUTATION_BONUS_PER_EPOCH:=0}"
: "${TD_HS_REPUTATION_MIN_WEIGHT:=1}"
: "${TD_HS_REPUTATION_MAX_WEIGHT:=100}"
: "${TD_HS_REPUTATION_LEADER_MISS_PENALTY_ENABLE:=1}"
: "${TD_HS_WEIGHT_UPDATE_ENABLE:=1}"
: "${TD_HS_WEIGHT_UPDATE_EPOCH_VIEWS:=512}"
: "${TD_HS_WEIGHT_UPDATE_ACTIVATION_EPOCH_DELAY:=1}"
: "${TD_HS_LEADER_SELECTION_ENABLE:=1}"
: "${TD_HS_LEADER_PROFILE_UPDATE_ENABLE:=1}"
: "${TD_HS_LEADER_ELIGIBLE_MIN_WEIGHT:=10}"
: "${TD_HS_BENCHMARK_DYNAMIC_ROUTING_ENABLE:=1}"
: "${TD_HS_BENCHMARK_RETRY_ENABLE:=1}"
: "${TD_HS_BENCHMARK_REQUEST_TIMEOUT_MS:=500}"
: "${TD_HS_REQUEST_VIEW_LOOKAHEAD:=20}"
: "${TD_HS_WEIGHT_PLUGIN_DRAIN_INTERVAL_VIEWS:=256}"
: "${TD_HS_QC_DIVERSITY_ENABLE:=1}"
: "${TD_HS_QC_SIGNER_COOLDOWN_ROUNDS:=1}"
: "${TD_HS_TIMEOUT_ENABLE:=0}"
: "${TD_HS_TIMEOUT_MS:=500}"
: "${TD_HS_SILENT_LEADER_IDS:=}"

export TD_HS_WEIGHTS
export TD_HS_REPUTATION_ENABLE
export TD_HS_REPUTATION_WINDOW_SIZE
export TD_HS_REPUTATION_QUEUE_CAPACITY
export TD_HS_REPUTATION_MAX_DELTA
export TD_HS_REPUTATION_DECAY_PER_EPOCH
export TD_HS_REPUTATION_MAX_RECOVERY_PER_EPOCH
export TD_HS_REPUTATION_BONUS_PER_EPOCH
export TD_HS_REPUTATION_MIN_WEIGHT
export TD_HS_REPUTATION_MAX_WEIGHT
export TD_HS_REPUTATION_LEADER_MISS_PENALTY_ENABLE
export TD_HS_WEIGHT_UPDATE_ENABLE
export TD_HS_WEIGHT_UPDATE_EPOCH_VIEWS
export TD_HS_WEIGHT_UPDATE_ACTIVATION_EPOCH_DELAY
export TD_HS_LEADER_SELECTION_ENABLE
export TD_HS_LEADER_PROFILE_UPDATE_ENABLE
export TD_HS_LEADER_ELIGIBLE_MIN_WEIGHT
export TD_HS_BENCHMARK_DYNAMIC_ROUTING_ENABLE
export TD_HS_BENCHMARK_RETRY_ENABLE
export TD_HS_BENCHMARK_REQUEST_TIMEOUT_MS
export TD_HS_REQUEST_VIEW_LOOKAHEAD
export TD_HS_WEIGHT_PLUGIN_DRAIN_INTERVAL_VIEWS
export TD_HS_QC_DIVERSITY_ENABLE
export TD_HS_QC_SIGNER_COOLDOWN_ROUNDS
export TD_HS_TIMEOUT_ENABLE
export TD_HS_TIMEOUT_MS
export TD_HS_SILENT_LEADER_IDS
